# Generated by Django 2.2 on 2019-04-05 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('barcode_listener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-modified_at', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='alias',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='msrp',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='newupc',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='rate_down',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='rate_up',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='st0s',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='upcnumber',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
