# Generated by Django 2.2 on 2019-04-05 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('barcode_listener', '0002_auto_20190405_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_use_by', models.DateTimeField(blank=True)),
                ('quantity_remaining', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(blank=True)),
                ('modified_at', models.DateTimeField(blank=True)),
                ('product',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcode_listener.Product')),
            ],
            options={
                'ordering': ['-modified_at', '-created_at'],
            },
        ),
    ]
