# Generated by Django 2.2 on 2019-04-06 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('barcode_listener', '0005_auto_20190406_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age',
        ),
        migrations.RemoveField(
            model_name='product',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='error',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='product',
            name='msrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='newupc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate_down',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rate_up',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='st0s',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
