# Generated by Django 2.2 on 2019-04-19 12:44

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('barcode_listener', '0006_auto_20190406_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_source',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                  through='barcode_listener.TaggedProduct', to='taggit.Tag',
                                                  verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.',
                                                  through='barcode_listener.TaggedStock', to='taggit.Tag',
                                                  verbose_name='Tags'),
        ),
    ]
