# Generated by Django 2.2 on 2019-04-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('barcode_listener', '0007_auto_20190419_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_source',
            field=models.CharField(blank=True, default='Placeholder', max_length=128),
        ),
    ]
