# Generated by Django 2.2 on 2019-04-20 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('barcode_listener', '0008_auto_20190419_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_started',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
