# Generated by Django 2.2 on 2019-04-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('barcode_listener', '0009_stock_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
