# Generated by Django 2.2 on 2019-04-22 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('barcode_listener', '0010_auto_20190420_1840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='ControlStack',
        ),
        migrations.AlterModelOptions(
            name='controlstack',
            options={'ordering': ['pk'], 'verbose_name_plural': 'ControlStack'},
        ),
    ]
